name: Daily Update Index

on:
  schedule:
    - cron: "0 16 * * *" # 每天UTC 16:00 (北京时间凌晨0:00)
  workflow_dispatch: # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache data files
        uses: actions/cache@v2
        with:
          path: |
            ./*.json
            !./config.json
          key: ${{ runner.os }}-data-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-data-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          echo "$CONFIG_JSON" > config.json
          python indicesMaker.py

